[package]
name = "reasonable"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["sync", "time"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
